CREATE PROCEDURE uspInsRENTAL_FEE
@FeeID INT,
@RentalID INT
AS
BEGIN TRAN G1
INSERT INTO RENTAL_FEE (FeeID, RentalID)
	VALUES (@FeeID, @RentalID)
IF @@ERROR <> 0
	ROLLBACK TRAN G1
ELSE
	COMMIT TRAN G1
GO

-- Populate RENTAL_FEE
CREATE PROCEDURE uspPopulateRENTAL_FEE
@Num INT
AS
DECLARE @Run INT
DECLARE @FeeID INT
DECLARE @RentalID INT
DECLARE @FeeSize INT
DECLARE @RentalSize INT

SET @Run = 0
SET @FeeSize = (SELECT COUNT(*) FROM FEE)
SET @RentalSize = (SELECT COUNT(*) FROM RENTAL)

WHILE @Run < @Num
BEGIN
	SET @FeeID = (SELECT ROUND(RAND() * @FeeSize, 0))
	IF @FeeID IS NULL
		SET @FeeID = (SELECT ROUND(RAND() * @FeeSize, 0))

	SET @RentalID = (SELECT ROUND(RAND() * @RentalSize, 0))
	IF @RentalID IS NULL
		SET @RentalID = (SELECT ROUND(RAND() * @RentalSize, 0))

	EXEC uspInsRENTAL_FEE
		@FeeID = @FeeID,
		@RentalID = @RentalID
	SET @Run = @Run + 1
END
GO

EXEC uspPopulateRENTAL_FEE
	 @Num = 500
GO
